Fix discarding chunk of data when write ends exactly in the end of the buffer.
DNedic/lfbb_cpp pull request #2
Opened 2023-04-15 17:15 UTC by KOLANICH

2023-04-15 21:18 UTC, DNedic requested changes
Thanks for the changes LGTM.

Just to summarize when this would happen in my understanding:
1. A write happens to write to the end of the buffer, `r` is higher than 0 but less than `w`
2. Because w is zeroed before i is set to w, now the data between i and size is considered invalid

2023-04-15 21:18 UTC, DNedic commented on lfbb_cpp/inc/lfbb_impl.hpp
>      /* Increment the write index and wrap to 0 if needed */
Can you fix the comment here?

2023-04-15 21:18 UTC, DNedic commented on lfbb_cpp/inc/lfbb_impl.hpp
> +    if (w == size) {
And add a comment here.

2023-04-16 08:34 UTC, KOLANICH commented on lfbb_cpp/inc/lfbb_impl.hpp
>      /* Increment the write index and wrap to 0 if needed */
Fixed.

2023-04-16 08:35 UTC, KOLANICH commented on lfbb_cpp/inc/lfbb_impl.hpp
> +    if (w == size) {
Fixed.

2023-04-16 12:59 UTC, merged